### ISSUE TITLE
RFC iWlz 24004 Wijzigen naam notificaties Dossierhouder en CoordinatorZorgThuis

### ISSUE THREAD

**Issue by Onincx** [iStandaarden/iWlz_RequestForChange#27]
### eDocs volgnummer

2024002367

### Korte probleem omschrijving

Voor de notificaties Beeindigde rol Dossierhouder zorgaanbieder en Beeindigde rol CoordinatorZorgThuis zorgaanbieder klopt de naam van de notificatie niet. De 'Beeindigde rol' in de naam doet vermoeden dat je als zorgaanbieder niet meer de Dossierhouder of CoordinatorZorgThuis bent. De notificatie wordt echter verzonden als de einddatum van de Dossierhouder of Coordinator wordt gevuld of wordt gewijzigd. De einddatum kan ook leeg worden gemaakt.

Deze RFC beschrijft het voorstel om de namen van deze notificaties aan te passen zodat de werking van de notificaties helder is en de naam daarmee overeenkomt.

### Korte omschrijving voorgestelde oplossing

De volgende wijzigingen worden in deze RFC voorgesteld:

**Notificatie 'Beeindigde rol Dossierhouder zorgaanbieder':**
Wijziging naam

**Notificatie 'Beeindigde rol CoordinatorZorgThuis zorgaanbieder':**
Wijziging naam

### RFC gevolgen voor het onderdeel/de onderdelen

Documentatie / Afsprakenstelsel

### Welk ander onderdeel?

Notificaties

### Betrokken partij RFC

Zorgkantoor, Zorgaanbieder

### Indiener RFC

Zorginstituut

### Rol referentiegroep (BRG)

Informeren

## Analyse
**Huidige situatie**
De naam van de notificaties Beëindigde rol Dossierhouder zorgaanbieder en Beëindigde rol CoordinatorZorgThuis zorgaanbieder past niet bij de trigger van de notificatie

## Wijzigingsvoorstel
**Voorstel aanpassing naam notificaties**
Voorgesteld wordt om de naam van de genoemde notificaties te wijzigen zodat de naam in lijn is met de functionele werking van deze notificaties.

**Voordelen**

1. Voor alle ketenpartijen is het duidelijk wat de redenen (triggers) zijn om de notificatie te sturen.
2. De naam van de notificatie past bij de werking van de notificatie.

## Uitwerking wijzigingsvoorstel per onderdeel

**ERD**
N.v.t.

**Regels**
N.v.t.

**Notificaties**:
De onderstaande bestaande notificaties worden aangepast:

**Notificatie 'Beeindigde rol Dossierhouder zorgaanbieder':**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| **OUD**: Beeindigde rol Dossierhouder zorgaanbieder| **OUD**: Notificatie aan de zorgaanbieder wanneer zijn rol van Dossierhouder eindigt of de einddatum wijzigt |  **OUD**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling en de einddatum is gewijzigd of wordt ingevuld in Dossierhouder|
| **NIEUW**: BRN0009: Gewijzigde dossierhouder zorgaanbieder               |Notificatie aan de zorgaanbieder als het verantwoordelijke zorgkantoor de periode van de rol van Dossierhouder van deze zorgaanbieder heeft gewijzigd. |Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling in de Dossierhouder waarvan de periode is gewijzigd.|

**Notificatie 'Beeindigde rol CoordinatorZorgThuis zorgaanbieder':**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| **OUD**: Beeindigde rol CoordinatorZorgThuis zorgaanbieder| **OUD**: Notificatie aan de zorgaanbieder wanneer zijn rol van CoordinatorZorgThuis eindigt of de einddatum wijzigt |  **OUD**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling en de einddatum is gewijzigd of wordt ingevuld in CoordinatorZorgtThuis|
| **NIEUW**: BRN0012: Gewijzigde CoordinatorZorgtThuis zorgaanbieder               | Notificatie aan de zorgaanbieder als het verantwoordelijke zorgkantoor de periode van de rol van Coordinator zorg thuis van deze zorgaanbieder heeft gewijzigd.  |Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling in de CoordinatorZorgThuis waarvan de periode is gewijzigd. |

### Oplossing

| Oplossing     | Voordeel / Nadeel                | Overweging Referentiegroep |
| :------------ | :------------------------------- | :------------------------- |
| 1. Doorvoeren voorgestelde oplossing | **Voordeel**: De naam van de notificaties zijn in lijn met de functionele werking van de notificatie      |                            |
|               | **Voordeel**: Het is voor alle ketenpartijen duidelijk wat de werking van de notificaties is  |                            |
| 2. Niets doen | **Nadeel**: probleem blijft aanwezig  |                            |
|               |  |                            |

## Conclusie

RFC doorvoeren

### Gekozen oplossing

Oplossing 1.

### Publicatiemoment

Nog te bepalen

### Implementatiemoment

Bemiddelingsregister 1

### controleer project en labels van het issue

- [X] gecontroleerd////////

**Comment by IZijlstra** [comment]
Naam van notificatie: hierin gebruiken we in enkele gevallen wel en in andere gevallen geen hoofdletter(s). We zouden de letterlijke namen van de entiteiten en attributen kunnen opnemen.

**Comment by Onincx** [comment]
Naam en de inhoud van de RFC aangepast naar aanleiding van ontvangen reviewcommentaar.

**Comment by IZijlstra** [comment]
18-07-2024
Teksten notificaties gewijzigd zodat deze overeenkomen met de tekstvoorstellen die zijn opgenomen in RFC 24065. In deze RFC wordt een voorstel gedaan om notificaties en bijbehorende bedrijfsregels te uniformeren.

**Comment by RTrigg1** [comment]
Door RFC24059 en RFC24065 komt deze te vervallen en worden naamswijzigingen hierin doorgevoerd. #65 #59
