### ISSUE TITLE
RFC iWlz 24018 Verduidelijken werking notificatie Gewijzigde Zorgsamenstelling Zorgaanbieder

### ISSUE THREAD

**Issue by Onincx** [iStandaarden/iWlz_RequestForChange#41]
### eDocs volgnummer

2024015643

### Korte probleem omschrijving

Voor de notificatie 'Gewijzigde zorgsamenstelling zorgaanbieder' is onvoldoende beschreven wat de exacte triggers zijn om de notificatie te versturen. Dit zorgt voor onduidelijkheid bij de ketenpartijen.

### Korte omschrijving voorgestelde oplossing

De volgende wijziging wordt in deze RFC voorgesteld:

- Toevoegen van documentatie voor de notificatie 'Gewijzigde zorgsamenstelling zorgaanbieder'.

### RFC gevolgen voor het onderdeel/de onderdelen

Documentatie / Afsprakenstelsel

### Welk ander onderdeel?

Notificaties

### Betrokken partij RFC

Zorgkantoor, Zorgaanbieder

### Indiener RFC

Zorginstituut

### Rol referentiegroep (BRG)

Informeren

## Analyse
**Huidige situatie**
De notificatie 'Gewijzigde zorgsamenstelling zorgaanbieder' heeft momenteel de volgende documentatie: '_Stel notificatie op voor: de zorgaanbieder met de rol Dossierhouder of CoordinatorZorgThuis van de Client van wie de samenstelling van Bemiddelingspecificatie(s) is veranderd_'. 

**Bezwaren huidige situatie**
De huidige documentatie bij de notificatie geeft alleen aan dat de Dossierhouder of CoordinatorZorgThuis de notificatie ontvangt maar niet exact wanneer (wat zijn de specifieke triggers voor het sturen van de notificatie). Deze onduidelijkheid zorgt er potentieel voor dat ketenpartijen de notificatie op verschillende manieren implementeren.

## Wijzigingsvoorstel
**Toevoegen extra documentatie**
Voorgesteld wordt om documentatie aan de notificatie toe te voegen zodat duidelijk is wat de triggers zijn voor het genereren van de notificatie.

**Voordelen**

1. Voor alle ketenpartijen is het duidelijk wanneer de notificatie wordt verzonden
2. De Dossierhouder of de Coordinator zorg thuis ontvangt alleen een notificatie als een relevante wijziging in de samenstelling van de Bemiddelingspecificaties is doorgevoerd

## Uitwerking wijzigingsvoorstel per onderdeel
**ERD**
Het ERD hoeft hier niet op te worden aangepast.

**Regels**
De regels hoeven niet te worden aangepast

**Notificaties**:
De onderstaande bestaande notificatie wordt aangepast:

**Notificatie 'Gewijzigde zorgsamenstelling zorgaanbieder'**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| Gewijzigde zorgsamenstelling zorgaanbieder | Notificatie aan de zorgaanbieder met de rol Dossierhouder en/of Coordinator Zorg Thuis wanneer de samenstelling van een Bemiddeling (nieuwe of gewijzigde Bemiddelingspecificatie) wijzigt. |  **OUD**: Stel notificatie op voor: de zorgaanbieder met de rol Dossierhouder of CoordinatorZorgThuis van de Client van wie de samenstelling van Bemiddelingspecificatie(s) is veranderd |
|              |  | **NIEUW**: Stel notificatie op voor: de zorgaanbieder met de rol Dossierhouder of CoordinatorZorgThuis van de Client van wie de samenstelling van Bemiddelingspecificatie(s) (nieuwe of gewijzigde Bemiddelingspecificatie) wijzigt. De Dossierhouder ontvangt een notificatie als een Bemiddelingspecificatie wordt toegevoegd of wordt gewijzigd waarvan de Leveringsvorm is gevuld met Verblijf, VPT of DTV en de periode van deze Bemiddelingspecificatie (deels) overlapt met de eigen Dossierhouder periode. De Coordinator zorg thuis ontvangt een notificatie als een Bemiddelingspecificatie wordt toegevoegd of wordt gewijzigd waarvan de Leveringsvorm is gevuld met MPT en de periode van deze Bemiddelingspecificatie (deels) overlapt met de eigen Coordinator zorg thuis periode.|

### Oplossing

| Oplossing     | Voordeel / Nadeel                | Overweging Referentiegroep |
| :------------ | :------------------------------- | :------------------------- |
| 1. Doorvoeren voorgestelde oplossing | Voordeel: De triggers voor de notificatie zijn voor alle ketenpartijen duidelijk      |                            |
|               | Voordeel: De Dossierhouder en Coordinator zorg thuis ontvangt de notificatie alleen als een relevante wijziging in de samenstelling van de Bemiddelingspecificatie is doorgevoerd |                            |
|               | Nadeel: Wijziging informatiemodel nodig     |                            |
| 2. Niets doen | Voordeel: geen wijziging nodig   |                            |
|               | Nadeel: probleem blijft aanwezig |                            |

## Conclusie

None

### controleer project en labels van het issue

- [X] gecontroleerd///

**Comment by Onincx** [comment]
### eDocs volgnummer

2024002367

### Versienummer RFC

0.3

### Korte probleem omschrijving

Voor een aantal bestaande notificaties, die worden gebruikt vanuit het Bemiddelingsregister, is de werking veranderd. Deze gewijzigde werking is nog niet als documentatie bij de betreffende notificatie vastgelegd.  Deze RFC beschrijft het voorstel om de documentatie van de onderstaande notificaties aan te passen zodat de werking van de notificaties helder is:


Tevens wordt voorgesteld om ook de naam van de eerste twee notificaties aan te passen zodat deze beter bij de werking van de notificatie past.

### Korte omschrijving voorgestelde oplossing

De volgende wijzigingen worden in deze RFC voorgesteld:

**Notificatie 'Beeindigde rol Dossierhouder zorgaanbieder':**
Wijziging naam
Wijziging documentatie

**Notificatie 'Beeindigde rol Coordinatorzorgthuis zorgaanbieder':**
Wijziging naam
Wijziging documentatie

**Notificatie 'Gewijzigde bemiddelingspecificatie zorgaanbieder'**
Wijziging documentatie

**Notificatie 'Gewijzigde bemiddelingspecificatie zorgkantoor'**
Wijziging documentatie

**Notificatie 'Gewijzigde zorgsamenstelling zorgaanbieder'**
Wijziging documentatie

**Notificatie 'Overdracht zorgkantoor'**
Wijziging documentatie:

### RFC gevolgen voor het onderdeel/de onderdelen

Documentatie / Afsprakenstelsel

### Welk ander onderdeel?

Notificaties

### Betrokken partij RFC

Zorgkantoor, Zorgaanbieder

### Andere betrokken partij

_No response_

### Indiener RFC

Zorginstituut

### Andere organisatie / contactpersoon

_No response_

### Rol referentiegroep (BRG)

Informeren


## Analyse
**Huidige situatie**
De notificaties voor het Bemiddelingsregister hebben nog een naam en documentatie die past bij de initiële werking van het register. 

**Bezwaren huidige situatie**
Via RFC iWlz 2024008 worden aanpassingen doorgevoerd die impact hebben op de gegevens in het Bemiddelingsregister en de werking van de bijbehorende notificaties. De documentatie van de notificaties, en voor 2 notificaties ook de naam, zijn niet meer passend bij de werking van het register.

## Wijzigingsvoorstel
**Voorstel aanpassing proces**
Voorgesteld wordt om de documentatie (en in twee gevalen de naam) van de genoemde notificaties te wijzigen zodat deze gelijk zijn aan de functionele werking van deze notificaties.

**Voordelen**

1. De naam en de documentatie van de notificaties sluiten aan bij het doel en de functionele werking van deze signalen
2. Voor alle ketenpartijen is het duidelijk wat de redenen zijn om de notificatie sturen

## Uitwerking wijzigingsvoorstel per onderdeel
**ERD**
Het ERD hoeft hier niet op te worden aangepast.

**Regels**
De regels hoeven niet te worden aangepast

**Notificaties**:
De onderstaande bestaande notificaties worden aangepast:

**Notificatie 'Beeindigde rol Dossierhouder zorgaanbieder':**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| **OUD**: Beeindigde rol Dossierhouder zorgaanbieder| **OUD**: Notificatie aan de zorgaanbieder wanneer zijn rol van Dossierhouder eindigt of de einddatum wijzigt |  **OUD**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling en de einddatum is gewijzigd of wordt ingevuld in Dossierhouder|
| **NIEUW**: Gewijzigde periode rol dossierhouder zorgaanbieder               | **NIEUW**: Notificatie aan de zorgaanbieder wanneer de periode van zijn rol van Dossierhouder wijzigt of is komen te vervallen. |**NIEUW**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling en de periode is gewijzigd of is komen te vervallen in Dossierhouder |


**Notificatie 'Beeindigde rol Coordinatorzorgthuis zorgaanbieder':**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| **OUD**: Beeindigde rol Coordinatorzorgthuis zorgaanbieder| **OUD**: Notificatie aan de zorgaanbieder wanneer zijn rol van Coordinatorzorgthuis eindigt of de einddatum wijzigt |  **OUD**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling en de einddatum is gewijzigd of wordt ingevuld in Coordinatorzorgthuis|
| **NIEUW**: Gewijzigde periode rol Coordinatorzorgthuis zorgaanbieder               | **NIEUW**: Notificatie aan de zorgaanbieder wanneer de periode van zijn rol van Coordinatorzorgthuis wijzigt of is komen te vervallen. |**NIEUW**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling en de periode is gewijzigd of is komen te vervallen in Coordinatorzorgthuis |


**Notificatie 'Gewijzigde bemiddelingspecificatie zorgaanbieder'**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| Gewijzigde bemiddelingspecificatie zorgaanbieder | **OUD**: Notificatie aan de zorgaanbieder wanneer zijn Bemiddelingspecificatie wijzigt |  **OUD**: Stel notificatie op voor: de zorgaanbieder die geregistreerd is onder instelling in de gewijzigde Bemiddelingspecificatie|
|              | **NIEUW**: Notificatie aan de zorgaanbieder wanneer zijn Bemiddelingspecificatie wijzigt of is komen te vervallen ||


**Notificatie 'Gewijzigde bemiddelingspecificatie zorgkantoor'**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| Gewijzigde bemiddelingspecificatie zorgkantoor | **OUD**: Notificatie aan het (bovenregionale) zorgkantoor wanneer de Bemiddelingspecificatie van een gecontracteerde zorgaanbieder wijzigt. |  **OUD**: Stel notificatie op voor: het zorgkantoor dat geregistreerd is onder uitvoerendzorgkantoor in de Bemiddelingspecificatie en niet ook het verantwoordelijkzorgkantoor is van de Bemiddeling |
|              | **NIEUW**: Notificatie aan het (bovenregionale) zorgkantoor wanneer de Bemiddelingspecificatie van een gecontracteerde zorgaanbieder wijzigt of is komen te vervallen ||


**Notificatie 'Gewijzigde zorgsamenstelling zorgaanbieder'**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| Gewijzigde zorgsamenstelling zorgaanbieder | **OUD**: Notificatie aan de zorgaanbieder met de rol Dossierhouder en/of Coordinator Zorg Thuis wanneer de samenstelling van een Bemiddeling (nieuwe of gewijzigde Bemiddelingspecificatie) wijzigt. |  **OUD**: Stel notificatie op voor: de zorgaanbieder met de rol Dossierhouder of CoordinatorZorgThuis van de Client van wie de samenstelling van Bemiddelingspecificatie(s) is veranderd |
|              | **NIEUW**: Notificatie aan de zorgaanbieder met de rol Dossierhouder en/of Coordinator Zorg Thuis wanneer de samenstelling van een Bemiddeling (nieuwe of gewijzigde Bemiddelingspecificatie) wijzigt of is komen te vervallen. | **NIEUW**: Stel notificatie op voor: de zorgaanbieder met de rol Dossierhouder of CoordinatorZorgThuis van de Client van wie de samenstelling van Bemiddelingspecificatie(s) is veranderd of is komen te vervallen |


**Notificatie 'Overdracht zorgkantoor'**

| Notificatie| Documentatie| Toelichting|
| :------------ | :------------------------------- | :------------------------- |
| Overdracht zorgkantoor | **OUD**: Notificatie aan het zorgkantoor wanneer een client aan hem wordt overgedragen. |  **OUD**: Stel notificatie op voor: het zorgkantoor dat geregistreerd is onder verantwoordelijkZorgkantoor in Overdracht |
|              | **NIEUW**: Notificatie aan het zorgkantoor wanneer een client aan hem wordt overgedragen of een eerder overdracht is komen te vervallen. |  |


### Oplossing

| Oplossing     | Voordeel / Nadeel                | Overweging Referentiegroep |
| :------------ | :------------------------------- | :------------------------- |
| 1. Doorvoeren voorgestelde oplossing | Voordeel: De naam en documentatie van de notificaties zijn in lijn met de functionele werking en het doel van de notificatie      |                            |
|               | Voordeel: Het is voor alle ketenpartijen duidelijk wat de werking van de notificaties is  |                            |
|               | Nadeel: Wijziging informatiemodel nodig     |                            |
| 2. Niets doen | Voordeel: geen wijziging nodig   |                            |
|               | Nadeel: probleem blijft aanwezig |                            |


## Conclusie

None

### Gekozen oplossing

_No response_

### Publicatiemoment

_No response_

### Implementatiemoment

_No response_

### controleer project en labels van het issue

- [X] gecontroleerd

**Comment by rvanrest** [comment]
zie ook #59 en #60 
Vermoedelijk impact

**Comment by IZijlstra** [comment]
18-07-2024: i.o.m. Remo en Richard deze RFC laten vervallen, vanwege nieuwe RFC 24065. In deze RFC is een voorstel uitgewerkt voor het uniformeren van notificaties en bijbehorende bedrijfsregels. Daarin zijn alle bestaande en nieuwe notificaties opgenomen.

https://github.com/iStandaarden/iWlz_RequestForChange/issues/65
